# Generated by Django 3.2 on 2021-10-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_index', '0002_auto_20211015_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_pub_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_photo_path',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
