# Generated by Django 3.2 on 2021-10-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_index', '0005_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_own_article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_index.article'),
        ),
    ]
