# Generated by Django 3.2 on 2021-11-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_index', '0007_alter_userinfo_user_own_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_own_article',
        ),
        migrations.AddField(
            model_name='article',
            name='article_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_index.userinfo'),
        ),
    ]
