# Generated by Django 3.2 on 2021-11-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_index', '0008_auto_20211101_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_photo_path',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
